---
apiVersion: v1
kind: Namespace
metadata:
  name: cleanfolio-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cleanfolio-ns
  name: cleanfolio-app
spec:
  selector:
    matchLabels:
      name: cleanfolio-app
  replicas: 3
  template:
    metadata:
      labels:
        name: cleanfolio-app
    spec:
      containers:
      - image: martinklapacz/cleanfolio:latest
        imagePullPolicy: Always
        name: cleanfolio-app
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  namespace: cleanfolio-ns
  name: cleanfolio-svc
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
  selector:
    name: cleanfolio-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cleanfolio-ingress
  namespace: cleanfolio-ns
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cleanfolio-svc
                port:
                  number: 80