apiVersion: v1
kind: Service
metadata:
  namespace: cleanfolio-ns
  name: cleanfolio-svc
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
  selector:
    name: cleanfolio-app